auto: true
server: true
permalink: /:title
baseurl: /3030-prototype
rooturl: "/_posts"
siteurl: ""
media: "/media"
prose:
  metadata:
    _posts:
      - name: "stat"
        field:
          element: "number"
          label: "Stat/Number"
      - name: "desc"
        field:
          element: "text"
          label: "Item Text"
          value: "default"
      - name: "link"
        field:
          element: "text"
          label: "link"
          value: "default"
      - name: "type"
        field:
          element: "select"
          label: "Link Type"
          placeholder: "Select and Item"
          options:
            - name: "Image"
              value: "Image"
            - name: "PDF"
              value: "pdf"
            - name: "Video"
              value: "video"
            - name: "Webpage"
              value: "webpage"
      - name: "item"
        field:
          element: "text"
          label: "Item Text"
          value: "default"
