auto: true
server: true
permalink: /:title
baseurl: /3030-prototype
rooturl: "/_posts"
siteurl: ""
media: "/media"
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          options:
            - name: "post"
              value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Year"
          value: "default"
      - name: "published"
        field:
          element: "select"
          label: "Publish"
          placeholder: "Publish this item"
          options:
            - name: "True"
              value: "true"
            - name: "false"
              value: "false"
      - name: "timeline"
        field:
          element: "select"
          label: "Timeline Display"
          placeholder: "Choose to display the timeline or not"
          options:
            - name: "Yes"
              value: "true"
            - name: "No"
              value: "false"
      - name: "teaserText"
        field:
          element: "text"
          label: "Teaser Text"
          value: "default"
      - name: "subtitle"
        field:
            element: "text"
            label: "Subtitle"
            value: "default"
      - name: "video"
        field:
            element: "text"
            label: "Video Link"
            value: "default"
      - name: "teaserImg"
        field:
            element: "text"
            label: "Teaser Image"
            value: "default"